# Plugins and dependencies
gems:         [ 'jekyll/scholar',
                'jekyll-archives' ]
markdown:     redcarpet
highlighter:  pygments

# Setup
title:       Nicolas De Jay
tagline:     ''
description: ''
url:         'http://nicolasdejay.com'
baseurl:     /
paginate:    5
permalink:   pretty

# Deploy settings
safe:        false
username:    'ndejay'
destination: '_site'

# jekyll-scholar settings

scholar:
  style:                 apa
  locale:                en
# sort-by:               asd
  order:                 ascending
  source:                ./_bibliography
# bibliography:          papers.bib
  bibliography_template: bib

# jekyll-archives settings

jekyll-archives:
  enabled:    [ 'year', 'month', 'tags' ]
  layouts:
    year:     archive-year
    month:    archive-month
    tag:      archive-tag
  permalinks:
    year:     '/:year/'
    month:    '/:year/:month/'
    day:      '/:year/:month/:day/'
    tag:      '/tag/:name/'
    category: '/category/:name/'

# Misc
include: [ 'feed.xml', 'CNAME' ]
exclude: [ 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor', '.travis.yml' ]
