# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Nicolas De Jay
tagline:          ''
description:      ''
url:              http://nicolasdejay.com
baseurl:          /

author:
  name:           'Nicolas De Jay'
  url:            https://twitter.com/mdo

paginate:         5

# Deploy settings
safe:             false
username:         'ndejay'
destination:      '_site'

# Misc
include:          [ 'feed.xml', 'CNAME' ]
exclude:          [ 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor', '.travis.yml' ]
