# Plugins and dependencies
gems:         [ 'jekyll-archives' ]
markdown:     redcarpet
highlighter:  pygments

# Setup
title:       Nicolas De Jay
tagline:     ''
description: ''
url:         'http://nicolasdejay.com'
baseurl:     /
paginate:    5
permalink:   pretty

# Deploy settings
safe:        false
username:    'ndejay'
destination: '_site'

# jekyll-archives settings

jekyll-archives:
  enabled:    [ 'year', 'month', 'tags' ]
  layouts:
    year:     archive_index_by_date
    month:    archive_index_by_date
    tag:      archive_index_by_category_or_tag
  permalinks:
    year:     '/:year/'
    month:    '/:year/:month/'
    tag:      '/tag/:name/'

# _plugins/archive_index.rb

archive_index:
  layout:      archive_index
  target:      archives
  fill:
    months:    false

# _plugins/publication_index.rb

publication_index:
  source:      _publications.bib
  layout:      publication_index
  target:      publications

# Misc
include: [ 'feed.xml', 'CNAME' ]
exclude: [ 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor', '.travis.yml' ]
