# Site settings
title: Your awesome title sandaru
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://url.herokuapp.com" # the base hostname & protocol for your site

# SASS settings
sass:
  sass_dir: _sass
  style: compressed

# Strip .html extension
permalink: pretty
defaults: ''
scope:
  path: ''
  type: 'posts'
  values:
    permalink: /:year/:month/:day/:title/

# Misc 
include: ['feed.xml']
exclude: ['Gemfile', 'Gemfile.lock', 'Procfile', 'sinatra.rb', 'Rakefile', 'vendor', 'tmp']
