# Plugins
gems:             [ 'jekyll/scholar' ]

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas De Jay
tagline:          ''
description:      ''
url:              'http://nicolasdejay.com'
baseurl:          /

paginate:         5

# Deploy settings
safe:             false
username:         'ndejay'
destination:      '_site'

# jekyll-scholar settings

scholar:
  style:          apa
  locale:         en
# sort-by:        asd
  order:          ascending
  source:         ./_bibliography
# bibliography:   papers.bib
  bibliography_template: bib

# Misc
include:          [ 'feed.xml', 'CNAME' ]
exclude:          [ 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor', '.travis.yml' ]
