source 'https://rubygems.org'

gem 'rake'
gem 'github-pages'
gem 'html-proofer'

# _plugins/publication_index.rb
gem 'bibtex-ruby'
gem 'citeproc-ruby'
gem 'csl-styles'

gem 'jekyll-sass'

group :jekyll_plugins do
  gem 'jekyll-archives'
end
